version: 2

updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/**
    groups:
      gh-actions:
        update-types:
          - minor
          - patch
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Europe/London
